# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f59ba36bec6783f4a9648f4e3bccb2b80e6bdff01c47698dee2a30671f13e023f6997f0c53eef9809e083ec99ab1890ed70dd9d3c0eaef74f2468827b1a3bc91

test:
  secret_key_base: ec7e194fe8afeddbb7a208f0dd7ad4e731bc22f3547ac31e015489a25c0eb7b0eb912a6adf485b0821ad8237dbaa44533209cbe2ea04598be92554d013b8d1ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
